### ISSUE TITLE
assets directory missing from the 1.0.0 release

### ISSUE THREAD

**Issue by steven1350** [pressbooks/pressbooks-aldine#104]
The `assets` directory is missing from your 1.0.0 release, causing some issues

**Comment by greatislander** [comment]
Can you be a bit more specific? The `assets` directory contains uncompiled/transpiled assets; the production release should be loading everything from `/dist`. Also, please use the issue template in future issues—filling out specifics like "expected behaviour" vs "actual behaviour" helps me triage these issues and quickly resolve theme without having to bother the reporter with follow-up questions. Cheers!

**Comment by steven1350** [comment]
Sorry, no problem. I will use the template in the future.

However to elaborate, on the production release, I noticed that some elements, such as the background image on the homepage, seem to be pointing to an /assets directory which is absent from the release. Looking over at the rest of the source, everything is using the /dist folder, so its possible this issue is just limited to the homepage background image

**Comment by greatislander** [comment]
Thanks for clarifying, I'll check this out.
