### ISSUE TITLE
Setup PHPUnit for Aldine, run tests as part of Travis build, set up CodeCov for repo

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-aldine#220]
Can imitate Pressbooks-book. Can do this with wp scaffold theme-tests (https://developer.wordpress.org/cli/commands/scaffold/theme-tests/). Might need to remove some default files (phpcs, etc).

**Comment by richard015ar** [comment]
@SteelWagstaff PR was approved. I think would be nice to update the documentation for this repo, adding the new changes.

**Comment by richard015ar** [comment]
@SteelWagstaff I confirm we don't have docs to the repo level for unit test in themes, we just have a general docs here: https://docs.pressbooks.org/unit-testing/ , I thought probably this repo required the same documentation we have for other repos as Fetcher or PB front end apps. But, in order to keep coherence with other themes, we could keep it as it and think in create a better documentation centralized for our unit tests on themes (and improve for plugins as well), just like @arzola proposed in our last retro meeting. It could be added in this task: https://github.com/pressbooks/private/issues/398 and in pressbooks.docs.

In my opinion this task is done @SteelWagstaff.
